# Server Setting
server:
  port: 5000
  ssl:
    enabled: false

spring:
  # RabbitMQ
  main:
    banner-mode: off
  zipkin:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  template:
    exchange:
      name: externalApiExchange
      type: direct

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # MariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://i9a403.p.ssafy.io/hyejin
    username: root
    password: D8C74FDD9DC1E2B7C2D7F5833C7CF51461904456EE6C0DC65303D9B9D38B346C

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #        dialect: org.hibernate.dialect.H2Dialect

  # Security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 576948301615-rulk67ue42f71ef21f127k8it1leoltd.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:5000/{action}/oauth2/code/{registrationId}"
            scope: profile,email  # 받아올 범위

# RabbitMQ Alias
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

# Openvidu Alias
OPENVIDU_URL: https://i9a403.p.ssafy.io:8443
OPENVIDU_SECRET: MY_SECRET

# JWT Alias
jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: fortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforufortuneforu

# Client Alias
client:
  host: localhost:8080
  url: http://localhost:8080
  endpoint: /redirect

# Logging level
logging:
  level:
    com:
      ssafy:
        a403: trace
