server:
  port: 8080
spring:
  main:
    banner-mode: off
  zipkin:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
queue:
  name: stt_queue
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus