# Server Setting
server:
  port: ${SERVER_PORT}
  ssl:
    enabled: false

spring:
  # RabbitMQ
  main:
    banner-mode: off
  zipkin:
    enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  template:
    exchange:
      name: externalApiExchange
      type: direct

  # MariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #        dialect: org.hibernate.dialect.H2Dialect

  # Security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope: profile,email  # 받아올 범위
          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
            
# RabbitMQ Alias
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

# Openvidu Alias
OPENVIDU_URL: ${OPENVIDU_URL}
OPENVIDU_SECRET: ${OPENVIDU_SECRET}

# JWT Alias
jwt:
  refresh-header: Refresh
  secret: ${JWT_SECRET}

# Client Alias
client:
  host: ${CLIENT_HOST}
  url: ${CLIENT_URL}
  endpoint: ${CLIENT_ENDPOINT}

# Logging level
logging:
  level:
    com:
      ssafy:
        a403: trace
